# Generated by Django 2.2.4 on 2019-08-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190822_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.FileField(blank=True, max_length=64, upload_to=['C:\\Users\\Renato Baetta\\Documents\\firstDjangoProject\\djangoBlog\\static']),
        ),
    ]
