# Generated by Django 2.2.4 on 2019-08-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190822_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(upload_to='blog/%Y/%m/%d'),
        ),
    ]
